label: Idioma
tips:
  language-overview:
    label: Idiomas
    body: '<p>The "Languages" page allows you to add, edit, delete, and reorder languages for the site.</p>'
  language-add:
    label: 'Añadiendo idiomas'
    body: '<p>Para añadir más idiomas a su sitio, haga clic en el botón "Añadir idioma".</p><p>Los idiomas añadidos se mostrarán en la lista de idiomas y pueden entonces ser editados o borrados.</p>'
  language-reorder:
    label: 'Reordenando idiomas'
  language-default:
    label: 'Establecer un idioma por defecto'
  language-operations:
    label: 'Modificando idiomas'
    body: '<p>Las operaciones son proporcionadas para editar y eliminar sus idiomas.</p><p>Puede editar el nombre y la dirección de un idioma.</p><p>Los idiomas eliminados pueden ser nuevamente añadidos en otro momento. Eliminar un idioma removerá todas las traducciones de la interfaz asociadas con él, y el contenido en este idioma será establecido como idioma neutral. Tenga en cuenta que no puede eliminar el idioma predeterminado para su sitio.</p>'
  language-continue:
    label: Continuando
