label: 'Editando idiomas'
tips:
  language-edit-overview:
    label: 'Editando idiomas'
    body: '<p>This page provides the ability to edit a language on your site, including custom languages.</p>'
  language-edit-langcode:
    label: 'Código de idioma'
    body: '<p>No puedes cambiar el código de un idioma en el sitio, ya que se usa en el sistema para asignar el idioma.</p>'
  language-edit-label:
    label: 'Nombre del idioma'
    body: '<p>El nombre del idioma es utilizado por todo el sitio para todos los usuarios y está escrito en inglés. Los nombres de idiomas incorporados pueden ser traducidos usando el módulo Interface Translation y los nombres de idiomas tanto incorporados como personalizados pueden ser traducidos usando el módulo Configuration Translation.</p>'
  language-edit-direction:
    label: 'Dirección del idioma'
    body: '<p>Escoja si el idioma es un idioma de "De izquierda a derecha" o de "De derecha a izquierda".</p><p>Fijese que no todos los temas soportan diseños de "De derecha a izquierda", por lo que debe probarlos antes si piensa usarlos.</p>'
  language-edit-continue:
    label: Continuando
