display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ anterior'
            next: 'siguiente ›'
            first: '« primero'
            last: 'última »'
      fields:
        subject:
          label: Subject
          separator: ', '
        name:
          separator: ', '
        contact_form_label:
          label: 'Contact form'
        created:
          label: Created
        operations:
          label: Operations
      filters:
        contact_form:
          expose:
            label: 'Contact form'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: List
