label: Archivo
description: 'Todo el contenido, por mes.'
display:
  default:
    display_title: Maestro
    display_options:
      title: 'Archivo mensual'
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Desplazamiento
          tags:
            previous: ‹‹
            next: ››
  block_1:
    display_title: Bloque
  page_1:
    display_title: Página
