label: Contenido
description: 'Encontrar y gestionar contenido.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de contenido'
          separator: ', '
        name:
          label: Autor
        status:
          label: Estado
        changed:
          label: Actualizado
        operations:
          label: Operaciones
      filters:
        status:
          expose:
            label: Estado
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
                value: '1'
              2:
                title: 'Sin publicar'
        type:
          expose:
            label: Tipo
        title:
          expose:
            label: Título
        langcode:
          expose:
            label: Idioma
      title: Contenido
      empty:
        area_text_custom:
          content: 'No hay contenido disponible.'
    display_title: Maestro
  page_1:
    display_options:
      menu:
        title: Contenido
      tab_options:
        title: Contenido
        description: 'Buscar y administrar contenido'
    display_title: Página
